[package]
id = edesm-project-management
version = 1.0.0
check_for_updates = false

[ui]
is_visible = true
label = EDESM Project Management

[launcher]
author = Benjamin
description = A project management tool for EDESM
version = 1.0.0

[install]
state = enabled
