name: Splunk CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fail if Dashboard Studio JSON dashboards exist
        run: |
          if find . -type f -name "*.json" | grep -q .; then
            echo "ERROR: Dashboard Studio JSON dashboards are not allowed."
            find . -type f -name "*.json"
            exit 1
          fi

      - name: Validate XML dashboards
        run: |
          echo "Validating XML dashboards..."
          for file in $(find . -type f -name "*.xml"); do
            echo "Checking $file"
            xmllint --noout "$file"
          done

      - name: Check required Splunk app files
        run: |
          echo "Checking required Splunk app files..."
          test -f default/app.conf || (echo "Missing default/app.conf" && exit 1)
          test -f metadata/local.meta || (echo "Missing metadata/local.meta" && exit 1)

  package-app:
    needs: validate-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build SPL package
        run: |
          echo "Building SPL package..."
          mkdir -p build
          tar -cvzf build/${{ github.event.repository.name }}.spl .
          ls -lh build

      - name: Upload SPL artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.spl
          path: build/${{ github.event.repository.name }}.spl

  deploy-app:
    needs: package-app
    runs-on: ubuntu-latest

    env:
      SPLUNK_BASE_URL: ${{ secrets.SPLUNK_BASE_URL }}
      SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download SPL artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.spl
          path: build

      - name: Verify SPL file exists
        run: |
          echo "Checking build directory..."
          ls -lh build

      #testing splunk connectivity
      - name: Test Splunk connectivity
        run: |
          curl -v ${SPLUNK_BASE_URL}/services/server/info

      - name: Install SPL package into Splunk
        run: |
          echo "Installing SPL package..."
          curl -k -X POST \
          -H "Authorization: Bearer ${SPLUNK_TOKEN}" \
          -H "Content-Type: application/octet-stream" \
          -H "Expect:" \
          --data-binary "@build/${{ github.event.repository.name }}.spl" \
          ${SPLUNK_BASE_URL}/services/apps/local?filename=true&update=true

#          curl -k -X POST \
#            -H "Authorization: Bearer ${SPLUNK_TOKEN}" \
#            -F "name=@build/${{ github.event.repository.name }}.spl" \
#            -F "filename=true" \
#            "${SPLUNK_BASE_URL}/services/apps/local"






